---
title: "STA302 Project"
subtitle: "What factors and how influence Ames Iowa Housing Sale Price"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r,message=FALSE,warning=FALSE}
library(MASS)
library(tidyverse)
library(magrittr)
library(gridExtra)
library(ggplot2)
library(car)
library(stargazer)
```





## Data 


```{r}
current_dir <- dirname(rstudioapi::getActiveDocumentContext()$path)
setwd(current_dir)
```


```{r}
ames_raw <- read.csv("../data/AmesHousing.csv")
```





```{r}
ames <- dplyr::select(ames_raw,`Central Air`, `Lot Shape`, `Garage Cars`, `Overall Qual`, `TotRms AbvGrd`, `Gr Liv Area`, `Garage Area`, `Fireplaces`, `SalePrice`)
ames <- na.omit(ames)
```



```{r}
rows <- sample(1:round(0.75*nrow(ames)), replace=FALSE) 
train<- ames[rows,]
test=ames[-rows,]
```



```{r}
summary(train[,-c(1,2)])
```

```{r}
### Categorical table
table(train$`Central Air`)
table(train$`Lot Shape`)
prop.table(table(train$`Central Air`))
prop.table(table(train$`Lot Shape`))
```

```{r}
summary(test[,-c(1,2)])
```

```{r}
table(test$`Central Air`)
table(test$`Lot Shape`)
prop.table(table(test$`Central Air`))
prop.table(table(test$`Lot Shape`))
```

## Visualization


```{r,fig.width=10,fig.height=12}
attach(train)
par(mfrow=c(4,2))
hist(SalePrice, breaks=10, main="",col="red")

hist(`Garage Area`, breaks=10, main="")
hist(`Gr Liv Area`, breaks=10, main="")

boxplot(`Overall Qual`, main = "",xlab="Overall Qual")
boxplot(`TotRms AbvGrd`, main = "",xlab="TotRms AbvGrd")

boxplot(`Fireplaces`, main = "",xlab="Fireplaces")

```


```{r,warning=FALSE,message=FALSE}
a=ggplot(data=train, aes(x=`Garage Area`, y=SalePrice)) + 
  geom_point() + 
  geom_smooth(method = lm, se = FALSE) + 
  labs(x = 'Garage Area', y='Sale Price')+
  theme_bw()


b=ggplot(data=train, aes(x=`Gr Liv Area`, y=SalePrice)) + 
  geom_point() + 
  geom_smooth(method = lm, se = FALSE) + 
  labs(x = 'Above grade (ground) living area square feet', y='Sale Price')+
  theme_bw()

grid.arrange(a,b, nrow=1)
```

## Model

```{r}
### Linear model full
full = lm(log(SalePrice) ~ ., data = train)
summary(full)
```

```{r}
m2 = lm(log(SalePrice) ~ .-`TotRms AbvGrd`, data = train)
summary(m2)
```


```{r}
# F test
anova(m2)
```

```{r}
m3 = lm(log(SalePrice) ~ `Central Air`+`Garage Cars`+`Overall Qual`+`Gr Liv Area`+`Garage Area`, data = train)
summary(m3)
```

```{r}
#Partial F test
anova(m2,m3)
```


Model checking

```{r,message=FALSE, echo=FALSE,warning=FALSE}
#condition 1
plot(train$SalePrice ~ exp(fitted(m2)), main="Y versus Y-hat", xlab="Y-hat", ylab="Y")
abline(a = 0, b = 1)
lines(lowess(train$SalePrice ~ exp(fitted(m2))), lty=2)
```


```{r,message=FALSE, echo=FALSE,warning=FALSE}
#condition 2
pairs(train[,-c(1,2)])
```

Model evaluation

```{r,message=FALSE, echo=FALSE,warning=FALSE}
par(mfrow=c(2,2))
plot(m2)
```



find outlier

```{r}
#find outlier
r <- rstandard(m2)
out <- which(r > 4 | r < -4)
out
```

```{r}
new_train = train[-out,]
```


```{r}
# determine whether there are leverage points
n <- nrow(new_train)
p <- length(coef(m2))-1
# leverage cutoff
h_cut <- 2*(p+1)/n 
off = which(hatvalues(m2) > h_cut)
off
```
```{r}
new_train = new_train[-off,]
```


```{r}
#cooks cutoff
D_cut <- qf(0.5, p+1, n-p-1)
which(cooks.distance(m2) > D_cut)
```

```{r}
#DFFITS cutoff
fits_cut <- 2*sqrt((p+1)/n) 
dff <- which(abs(dffits(m2)) > fits_cut)
dff
```
```{r}
new_train = new_train[-dff,]
```



```{r}
m4 = lm(log(SalePrice) ~ .-`TotRms AbvGrd`, data = new_train)
summary(m4)
```


```{r}
# F test
anova(m4)
```


Model checking

```{r,message=FALSE, echo=FALSE,warning=FALSE}
#condition 1
plot(new_train$SalePrice ~ exp(fitted(m4)), main="Y versus Y-hat", xlab="Y-hat", ylab="Y")
abline(a = 0, b = 1)
lines(lowess(new_train$SalePrice ~ exp(fitted(m4))), lty=2)
```


```{r,message=FALSE, echo=FALSE,warning=FALSE}
#condition 2
pairs(new_train[,-c(1,2)])
```

Model evaluation

```{r,message=FALSE, echo=FALSE,warning=FALSE}
par(mfrow=c(2,2))
plot(m4)
```




```{r}
r = resid(m4)
par(mfrow=c(1,3))
plot( r~ new_train$`Garage Area`, xlab="", ylab="residuals")
plot(r ~ new_train$`Garage Area`, xlab="", ylab="residuals")
qqnorm(r) 
qqline(r)
```


Multicollinearity test

```{r}
vif(m4)
```

```{r,warning=FALSE}
#export two models into one table. 
stargazer(full,m2,m3,m4, type="html",
          dep.var.labels=c("Log Sale Price"), out="train.htm")
```



The model checking for the validation model.

```{r,message=FALSE, echo=FALSE,warning=FALSE}
#model checking
m5=lm(log(SalePrice) ~ .-`TotRms AbvGrd`, data = test)
summary(m5)
```

```{r,message=FALSE, echo=FALSE,warning=FALSE}
par(mfrow=c(2,2))
plot(m5)
```



```{r,message=FALSE, echo=FALSE,warning=FALSE}
#model checking
r <- resid(m5)
# first check condition 1 and 2
#condition 1
plot(test$SalePrice ~ exp(fitted(m5)), main="Y versus Y-hat", xlab="Y-hat", ylab="Y")
abline(a = 0, b = 1)
lines(lowess(test$SalePrice ~ exp(fitted(m5))), lty=2)
```


```{r,message=FALSE, echo=FALSE,warning=FALSE}
#condition 2
# check conditions for checking model assumptions
pairs(test[,-c(1,2)])
```

```{r,warning=FALSE}
#export two models into one table. 
stargazer(m4,m5, type="html",
          dep.var.labels=c("Log Sale Price"), out="comp.htm")
```




































